destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/tam_-pdf"
port: 4011
output: pdf
product: tam_
print_title: TAM documentation
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: tam_sidebar
